#!/usr/bin/env bash
myvar="Hello"
echo "The value of myvar variable is; $myvar"
myvar="Bonjour!"
echo "The value of myvar variable is; $myvar"
declare -r myname="Firoz"
echo "The value of myname variable is; $myname"
myname="Firoz K A"
echo "The value of myname variable is; $myname"
declare -l mycity="Thiruvananthapuram"
echo "The value of mycity variable is; $mycity"
mycity="Kochi"
echo "The value of mycity variable is; $mycity"
declare -u mycountry="india"
echo "The value of mycountry variable is; $mycountry"
mycountry="united states"
echo "The value of mycountry variable is; $mycountry"